### PR TITLE
Migrated to Kotlin

### PR DESCRIPTION
**Pull request by poseidon2060**
- Migrated JAVA code to Kotlin

This PR solves issue #2 

Changes that I had to make:

1. Updated the `implementation 'com.google.ar:core:1.39.0'` implementation because the old one was giving error
2. Added Kotlin implementation and plugin in gradle files
3. Changed MainActivity and CustomArFragment classes from java to Kotlin

### CODE REVIEW

**Comment by poseidon2060** [comment]
@raghavtilak hey can you add `hacktoberfest-accepted` label to my PR please
Thankyou😇

**Comment by raghavtilak** [comment]
Hey @poseidon2060 . Please don't commit .idea files. These files are not project-specific. I will add a gitignore. But for now please commit ignoring these .idea folder files.

**Comment by poseidon2060** [comment]
Does this work or do I need to remove the previous commit/ open a new PR?
can you please assist me into how to remove those files from the PR

**Comment by poseidon2060** [comment]
hey @raghavtilak , can you please add `hacktoberfest-accepted` label to the PR please

**Comment by raghavtilak** [comment]
> Does this work or do I need to remove the previous commit/ open a new PR? can you please assist me into how to remove those files from the PR

You can always revert the commit. No issues. 
Great work 👍🏻 
Thanks for your contribution 😄

**Pull request merged**
